#!/usr/bin/env bash
# backup and compress my databases

# variables
DATE=$(date +"%d-%m-%Y")
file_name="$DATE.tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$file_name" backup.sql
