#!/usr/bin/env bash

# Update packages
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Check nginx status
sudo service nginx status

# Configure nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart nginx
sudo service nginx restart

# Check nginx status again
sudo service nginx status

