#!/usr/bin/env bash
# fix the container so that Nginx is running as the nginx user and
#+ listening on all active IPs on port 8080

# Install necessary packages
sudo apt-get update
sudo apt-get install -y nginx

# Stop nginx service
sudo service nginx stop

# Configure nginx to run as nginx user
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Configure nginx to listen on all active IPs on port 8080
sed -i 's/listen\s*80;/listen *:8080;/g' /etc/nginx/sites-available/default

# Start nginx service
sudo service nginx start
